name: 删除 workflows 和 deployment 记录
on:
# Run weekly, at 00:00 on sunday.
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflows runs for current repo
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 0
          keep_minimum_runs: 0

      - name: Delete deployment
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ github.token }}
          environment: github-pages
          onlyRemoveDeployments: true